package:
  name: pip
  version: 8.1.0

source:
  fn: pip-8.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pip/pip-8.1.0.tar.gz
  md5: e9c3844db343f47d16040b32ad9072be

build:
  entry_points:
    - pip = pip:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - wheel

test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip

about:
  home: http://www.pip-installer.org/
  license: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
